### PR TITLE
Use spiketoolkit for comparison

### PR DESCRIPTION
**Pull request by alejoe91**
- fixed speed issues by setting compute_misclassification to False

### CODE REVIEW

**Comment by alejoe91** [comment]
This works now with the master branches of spikeextractors, spikesorters, and spiketoolkit

https://github.com/SpikeInterface/spikeextractors/pull/203
https://github.com/SpikeInterface/spikesorters/pull/27
https://github.com/SpikeInterface/spiketoolkit/pull/190

@jeremy let me know if this solves the speed issue

**Comment by magland** [comment]
i am testing now (after the merge, haha)

**Comment by magland** [comment]
Seems to work okay, but it is still twice as slow for this particular example.

Here's the troubleshooting script: https://github.com/flatironinstitute/spikeforest/blob/master/working/scratch/troubleshoot_compare_gt.py

And here's my output:
```
Loading recording...
Compare with truth...
Job: GenSortingComparisonTable (version: 0.2.6)
Timestamp: 2019-07-01 15:29:25
Running processor directly...
GenSortingComparisonTable: firings=/home/magland/src/spikeforest/working/scratch/test_outputs/firings.mda, firings_true=/home/magland/src/spikeforest/working/scratch/test_outputs/firings_true.mda, units_true=[]
Saving output: /home/magland/sha1-cache-new/tmp/tmp_execute_outputdir_GenSortingComparisonTablefuc_r2iz/json_out.json -> /home/magland/src/spikeforest/working/scratch/test_outputs/comparison_old.json
Saving output: /home/magland/sha1-cache-new/tmp/tmp_execute_outputdir_GenSortingComparisonTablefuc_r2iz/html_out.html -> /home/magland/src/spikeforest/working/scratch/test_outputs/comparison_old.html
ELAPSED::::::::::::::: 4.2104551792144775
Job: GenSortingComparisonTableNew (version: 0.3.1)
Timestamp: 2019-07-01 15:29:29
Running processor directly...
GenSortingComparisonTable: firings=/home/magland/src/spikeforest/working/scratch/test_outputs/firings.mda, firings_true=/home/magland/src/spikeforest/working/scratch/test_outputs/firings_true.mda, units_true=[]
Warning: sampling frequency information not found. Setting delta_frames to 10.
Saving output: /home/magland/sha1-cache-new/tmp/tmp_execute_outputdir_GenSortingComparisonTableNewztumiil9/json_out.json -> /home/magland/src/spikeforest/working/scratch/test_outputs/comparison_new.json
Saving output: /home/magland/sha1-cache-new/tmp/tmp_execute_outputdir_GenSortingComparisonTableNewztumiil9/html_out.html -> /home/magland/src/spikeforest/working/scratch/test_outputs/comparison_new.html
ELAPSED::::::::::::::: 10.430731773376465
Compute units info...
----------------------------------------------------
RESULTS FOR old
Avg. accuracy for units with snr >= 8: 0.5419666666666667
----------------------------------------------------
RESULTS FOR new
Avg. accuracy for units with snr >= 8: 0.541340849507809
```

**Comment by alejoe91** [comment]
Ok we can try to improve it :) at least it's not 10-20 times slower!!!

**Pull request merged**
