### PR TITLE
New tridesclous params.

### PR DESCRIPTION
**Pull request by samuelgarcia**
Prepare new tag on spiketoolkit and tridesclous.

### CODE REVIEW

**Comment by magland** [comment]
I am merging it. Then I will create a new container and re-run the sf analysis pipeline. Might take a couple days to see the updated results.

**Comment by magland** [comment]
spiketoolkit 0.3.3 was not installable by pip in the docker build, so I am changing it back to 0.3.2 for now. Will it cause a problem @samuelgarcia?

**Comment by magland** [comment]
I confirm that on the unit test the new version does much better on synth_magland_c8. Now I'm re-running the whole analysis with new version and we'll see in a day or two.

**Comment by samuelgarcia** [comment]
I will release spiketoolkit 0.3.3 today.
The release 0.3.3 in ST make some difference on parameters for TDC to make them more "automatic".
I will tell you when the releae will be done. If you could rebuild the container it would be perfect.
thanks.

**Comment by magland** [comment]
Okay got it. Let me know when 0.3.3 is released.

**Comment by samuelgarcia** [comment]
Hi.
Released !!!

**Comment by samuelgarcia** [comment]
https://pypi.org/project/spiketoolkit/#history

**Pull request merged**
