### PR TITLE
Tridesclous version 1.2.2

### PR DESCRIPTION
**Pull request by samuelgarcia**
Try isosplit5 blindly :)

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeremy.
Do you think you could merge this ? I would like to try isosplit on tridesclous for low channel count and related perf.
Best
Samuel

**Comment by magland** [comment]
Merged. I guess I need to rebuild the container and increment the wrapper version?

**Comment by samuelgarcia** [comment]
Thanks a lot.
The container yes.
The wrapper is still the same.

**Comment by samuelgarcia** [comment]
Hi Jeremy.
I back from holiday.
I see on the website that tridesclous still have bugs for some datset (chen there is a *).
Normally this should have solve the bug. Does the last run included this 1.2.2 version of tridesclous ?

**Pull request merged**
